"""Change cardio_load to DECIMAL(5,2)

Revision ID: 049f640b2d4d
Revises: e66756258553
Create Date: 2025-11-16 20:03:39.994966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049f640b2d4d'
down_revision = 'e66756258553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polar_exercises', 'cardio_load',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=5, scale=2),
               comment='Polar训练负荷（保留两位小数）',
               existing_comment='Polar训练负荷',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polar_exercises', 'cardio_load',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=sa.INTEGER(),
               comment='Polar训练负荷',
               existing_comment='Polar训练负荷（保留两位小数）',
               existing_nullable=True)
    # ### end Alembic commands ###
