"""change_ai_recommendation_fields_to_jsonb

Revision ID: 05f5b4b62339
Revises: 61188417f539
Create Date: 2025-11-20 22:47:46.606675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05f5b4b62339'
down_revision = '61188417f539'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 由于数据格式完全改变（从Markdown文本改为结构化JSON），删除并重新创建字段
    # 用户可以重新生成新格式的建议

    # 先清空现有数据
    op.execute('DELETE FROM ai_recommendations')

    # 删除旧字段
    op.drop_column('ai_recommendations', 'yesterday_review')
    op.drop_column('ai_recommendations', 'today_recommendation')
    op.drop_column('ai_recommendations', 'health_education')

    # 创建新的JSONB字段
    op.add_column('ai_recommendations',
                  sa.Column('yesterday_review', postgresql.JSONB(astext_type=sa.Text()),
                           nullable=False, comment='昨日评价(JSON)'))
    op.add_column('ai_recommendations',
                  sa.Column('today_recommendation', postgresql.JSONB(astext_type=sa.Text()),
                           nullable=False, comment='今日建议(JSON)'))
    op.add_column('ai_recommendations',
                  sa.Column('health_education', postgresql.JSONB(astext_type=sa.Text()),
                           nullable=False, comment='健康科普(JSON)'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_recommendations', 'health_education',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               comment='健康科普',
               existing_comment='健康科普(JSON)',
               existing_nullable=False)
    op.alter_column('ai_recommendations', 'today_recommendation',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               comment='今日建议',
               existing_comment='今日建议(JSON)',
               existing_nullable=False)
    op.alter_column('ai_recommendations', 'yesterday_review',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               comment='昨日评价',
               existing_comment='昨日评价(JSON)',
               existing_nullable=False)
    # ### end Alembic commands ###
