"""Add Polar sleep and nightly recharge tables

Revision ID: 12c318e96331
Revises: 79ba7bc4ab5d
Create Date: 2025-11-21 14:54:20.831102

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12c318e96331'
down_revision = '79ba7bc4ab5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polar_nightly_recharge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('polar_id', sa.String(length=100), nullable=False, comment='Polar夜间恢复唯一ID'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('ans_charge', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='ANS恢复评分(0-100)'),
    sa.Column('ans_charge_status', sa.Integer(), nullable=True, comment='ANS状态(1-7: compromised到完全恢复)'),
    sa.Column('hrv_avg', sa.Integer(), nullable=True, comment='平均HRV(ms)'),
    sa.Column('breathing_rate_avg', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='平均呼吸频率(次/分)'),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True, comment='平均心率(bpm)'),
    sa.Column('rmssd', sa.Integer(), nullable=True, comment='RMSSD(ms)'),
    sa.Column('sleep_charge', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='睡眠恢复评分(0-100)'),
    sa.Column('sleep_charge_status', sa.Integer(), nullable=True, comment='睡眠状态(1-7)'),
    sa.Column('sleep_score', sa.Integer(), nullable=True, comment='睡眠评分(0-100)'),
    sa.Column('nightly_recharge_status', sa.Integer(), nullable=True, comment='总体恢复状态(1-7)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_polar_nightly_recharge_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polar_nightly_recharge')),
    sa.UniqueConstraint('polar_id', name=op.f('uq_polar_nightly_recharge_polar_id'))
    )
    op.create_index('idx_polar_recharge_user_date', 'polar_nightly_recharge', ['user_id', 'date'], unique=False)
    op.create_table('polar_sleep',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('polar_id', sa.String(length=100), nullable=False, comment='Polar睡眠唯一ID'),
    sa.Column('sleep_date', sa.Date(), nullable=False, comment='睡眠日期'),
    sa.Column('sleep_start_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='入睡时间'),
    sa.Column('sleep_end_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='醒来时间'),
    sa.Column('deep_sleep_duration', sa.Integer(), nullable=True, comment='深睡时长(秒)'),
    sa.Column('light_sleep_duration', sa.Integer(), nullable=True, comment='浅睡时长(秒)'),
    sa.Column('rem_sleep_duration', sa.Integer(), nullable=True, comment='REM睡眠时长(秒)'),
    sa.Column('total_interruption_duration', sa.Integer(), nullable=True, comment='总中断时长(秒)'),
    sa.Column('sleep_score', sa.Integer(), nullable=True, comment='睡眠评分(0-100)'),
    sa.Column('continuity', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='睡眠连续性'),
    sa.Column('continuity_class', sa.Integer(), nullable=True, comment='连续性分类(1-5)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_polar_sleep_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polar_sleep')),
    sa.UniqueConstraint('polar_id', name=op.f('uq_polar_sleep_polar_id'))
    )
    op.create_index('idx_polar_sleep_user_date', 'polar_sleep', ['user_id', 'sleep_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_polar_sleep_user_date', table_name='polar_sleep')
    op.drop_table('polar_sleep')
    op.drop_index('idx_polar_recharge_user_date', table_name='polar_nightly_recharge')
    op.drop_table('polar_nightly_recharge')
    # ### end Alembic commands ###
