"""Add health_reports table

Revision ID: 1f040524bbb7
Revises: 049f640b2d4d
Create Date: 2025-11-19 21:11:53.100671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f040524bbb7'
down_revision = '049f640b2d4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('training_data', sa.JSON(), nullable=True),
    sa.Column('sleep_data', sa.JSON(), nullable=True),
    sa.Column('readiness_data', sa.JSON(), nullable=True),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('stress_data', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('weekly_trends', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_reports_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_reports'))
    )
    op.create_index(op.f('ix_health_reports_report_date'), 'health_reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_reports_report_date'), table_name='health_reports')
    op.drop_table('health_reports')
    # ### end Alembic commands ###
