"""Add nutrition tables: meal_records, food_items, nutrition_daily_summary

Revision ID: 26b44259a555
Revises: 12c318e96331
Create Date: 2025-11-22 13:07:55.034266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26b44259a555'
down_revision = '12c318e96331'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype', native_enum=False), nullable=False, comment='餐次类型'),
    sa.Column('meal_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='用餐时间'),
    sa.Column('photo_path', sa.String(length=500), nullable=True, comment='原图存储路径'),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True, comment='缩略图路径'),
    sa.Column('total_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总热量 (kcal)'),
    sa.Column('total_protein', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总蛋白质 (g)'),
    sa.Column('total_carbs', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总碳水化合物 (g)'),
    sa.Column('total_fat', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总脂肪 (g)'),
    sa.Column('total_fiber', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总膳食纤维 (g)'),
    sa.Column('gemini_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Gemini完整输出（包含分析、建议等）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_records'))
    )
    op.create_index(op.f('ix_meal_records_meal_time'), 'meal_records', ['meal_time'], unique=False)
    op.create_index(op.f('ix_meal_records_user_id'), 'meal_records', ['user_id'], unique=False)
    op.create_table('nutrition_daily_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('total_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总热量 (kcal)'),
    sa.Column('total_protein', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总蛋白质 (g)'),
    sa.Column('total_carbs', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总碳水化合物 (g)'),
    sa.Column('total_fat', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总脂肪 (g)'),
    sa.Column('total_fiber', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='总膳食纤维 (g)'),
    sa.Column('meals_count', sa.Integer(), nullable=False, comment='餐次数量'),
    sa.Column('breakfast_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='早餐热量'),
    sa.Column('lunch_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='午餐热量'),
    sa.Column('dinner_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='晚餐热量'),
    sa.Column('snack_calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='加餐热量'),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='营养警示标记（如热量过高、蛋白质不足等）'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_daily_summary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_daily_summary'))
    )
    op.create_index(op.f('ix_nutrition_daily_summary_date'), 'nutrition_daily_summary', ['date'], unique=False)
    op.create_index(op.f('ix_nutrition_daily_summary_user_id'), 'nutrition_daily_summary', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False, comment='食物名称'),
    sa.Column('category', sa.Enum('STAPLE', 'PROTEIN', 'VEGETABLE', 'FRUIT', 'DAIRY', 'FAT', 'BEVERAGE', 'SNACK', 'OTHER', name='foodcategory', native_enum=False), nullable=True, comment='食物分类'),
    sa.Column('estimated_weight', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='估计重量 (g)'),
    sa.Column('calories', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='热量 (kcal)'),
    sa.Column('protein', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='蛋白质 (g)'),
    sa.Column('carbs', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='碳水化合物 (g)'),
    sa.Column('fat', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='脂肪 (g)'),
    sa.Column('fiber', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='膳食纤维 (g)'),
    sa.Column('sodium', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='钠 (mg)'),
    sa.Column('sugar', sa.DECIMAL(precision=8, scale=2), nullable=True, comment='糖分 (g)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_records.id'], name=op.f('fk_food_items_meal_id_meal_records'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_items'))
    )
    op.create_index(op.f('ix_food_items_meal_id'), 'food_items', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_items_meal_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_nutrition_daily_summary_user_id'), table_name='nutrition_daily_summary')
    op.drop_index(op.f('ix_nutrition_daily_summary_date'), table_name='nutrition_daily_summary')
    op.drop_table('nutrition_daily_summary')
    op.drop_index(op.f('ix_meal_records_user_id'), table_name='meal_records')
    op.drop_index(op.f('ix_meal_records_meal_time'), table_name='meal_records')
    op.drop_table('meal_records')
    # ### end Alembic commands ###
