"""add_sleep_score_delta_fields

Revision ID: 2a9c97d9a3da
Revises: 78b282d2c0dc
Create Date: 2025-11-27 21:17:04.334203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9c97d9a3da'
down_revision = '78b282d2c0dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oura_sleep', sa.Column('sleep_score_delta', sa.Integer(), nullable=True, comment='睡眠评分增量(午睡贡献,如+9)'))
    op.add_column('oura_sleep', sa.Column('readiness_score_delta', sa.Integer(), nullable=True, comment='准备度评分增量(午睡贡献)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oura_sleep', 'readiness_score_delta')
    op.drop_column('oura_sleep', 'sleep_score_delta')
    # ### end Alembic commands ###
