"""Remove unique constraint from ai_recommendations allow history

Revision ID: 2bdecefa54e2
Revises: 05f5b4b62339
Create Date: 2025-11-21 12:53:55.149241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bdecefa54e2'
down_revision = '05f5b4b62339'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生成时间',
               existing_nullable=False)
    op.drop_constraint('uq_user_date_ai', 'ai_recommendations', type_='unique')
    op.alter_column('oura_daily_activity', 'active_calories',
               existing_type=sa.INTEGER(),
               comment='活动消耗(千卡/kcal)',
               existing_comment='活动消耗卡路里',
               existing_nullable=True)
    op.alter_column('oura_daily_activity', 'total_calories',
               existing_type=sa.INTEGER(),
               comment='总消耗(千卡/kcal)',
               existing_comment='总消耗卡路里',
               existing_nullable=True)
    op.alter_column('oura_daily_readiness', 'resting_heart_rate',
               existing_type=sa.INTEGER(),
               comment='静息心率评分(0-100，非实际BPM)',
               existing_comment='静息心率',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oura_daily_readiness', 'resting_heart_rate',
               existing_type=sa.INTEGER(),
               comment='静息心率',
               existing_comment='静息心率评分(0-100，非实际BPM)',
               existing_nullable=True)
    op.alter_column('oura_daily_activity', 'total_calories',
               existing_type=sa.INTEGER(),
               comment='总消耗卡路里',
               existing_comment='总消耗(千卡/kcal)',
               existing_nullable=True)
    op.alter_column('oura_daily_activity', 'active_calories',
               existing_type=sa.INTEGER(),
               comment='活动消耗卡路里',
               existing_comment='活动消耗(千卡/kcal)',
               existing_nullable=True)
    op.create_unique_constraint('uq_user_date_ai', 'ai_recommendations', ['user_id', 'date'])
    op.alter_column('ai_recommendations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生成时间',
               existing_nullable=False)
    # ### end Alembic commands ###
