"""add birth_year to users

Revision ID: 45bd9fbdcf15
Revises: 1f040524bbb7
Create Date: 2025-11-20 01:03:59.579303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45bd9fbdcf15'
down_revision = '1f040524bbb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_recommendations', 'yesterday_assessment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='昨日数据评估',
               existing_nullable=True)
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True, comment='出生年份'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_year')
    op.alter_column('ai_recommendations', 'yesterday_assessment',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='昨日数据评估',
               existing_nullable=True)
    # ### end Alembic commands ###
