"""Refactor AI recommendations structure

Revision ID: 61188417f539
Revises: 45bd9fbdcf15
Create Date: 2025-11-20 15:53:58.620172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61188417f539'
down_revision = '45bd9fbdcf15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加新字段为nullable
    op.add_column('ai_recommendations', sa.Column('yesterday_review', sa.Text(), nullable=True, comment='昨日评价'))
    op.add_column('ai_recommendations', sa.Column('today_recommendation', sa.Text(), nullable=True, comment='今日建议'))
    op.add_column('ai_recommendations', sa.Column('health_education', sa.Text(), nullable=True, comment='健康科普'))

    # 填充默认值
    op.execute("""
        UPDATE ai_recommendations
        SET
            yesterday_review = '数据结构升级中，请重新生成建议',
            today_recommendation = '数据结构升级中，请重新生成建议',
            health_education = '数据结构升级中，请重新生成建议'
        WHERE yesterday_review IS NULL
    """)

    # 改为NOT NULL
    op.alter_column('ai_recommendations', 'yesterday_review', nullable=False)
    op.alter_column('ai_recommendations', 'today_recommendation', nullable=False)
    op.alter_column('ai_recommendations', 'health_education', nullable=False)

    # 删除旧字段
    op.drop_column('ai_recommendations', 'cardiovascular_insights')
    op.drop_column('ai_recommendations', 'yesterday_assessment')
    op.drop_column('ai_recommendations', 'risk_assessment')
    op.drop_column('ai_recommendations', 'training_advice')
    op.drop_column('ai_recommendations', 'action_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendations', sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='行动清单'))
    op.add_column('ai_recommendations', sa.Column('training_advice', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='训练建议'))
    op.add_column('ai_recommendations', sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='风险评估'))
    op.add_column('ai_recommendations', sa.Column('yesterday_assessment', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='昨日数据评估'))
    op.add_column('ai_recommendations', sa.Column('cardiovascular_insights', sa.TEXT(), autoincrement=False, nullable=True, comment='心血管健康分析'))
    op.drop_column('ai_recommendations', 'health_education')
    op.drop_column('ai_recommendations', 'today_recommendation')
    op.drop_column('ai_recommendations', 'yesterday_review')
    # ### end Alembic commands ###
