"""add breathing_regularity to oura_daily_spo2

Revision ID: 6a787ce31107
Revises: 8380bf62dc29
Create Date: 2025-11-23 15:41:55.020406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a787ce31107'
down_revision = '8380bf62dc29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oura_daily_spo2', sa.Column('breathing_regularity', sa.Integer(), nullable=True, comment='呼吸规律性评分(0-100)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oura_daily_spo2', 'breathing_regularity')
    # ### end Alembic commands ###
