"""add zone boundary fields to polar_exercises

Revision ID: 78b282d2c0dc
Revises: 6a787ce31107
Create Date: 2025-11-26 20:13:28.406487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b282d2c0dc'
down_revision = '6a787ce31107'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polar_exercises', sa.Column('zone1_lower', sa.Integer(), nullable=True, comment='Zone1下限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone1_upper', sa.Integer(), nullable=True, comment='Zone1上限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone2_lower', sa.Integer(), nullable=True, comment='Zone2下限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone2_upper', sa.Integer(), nullable=True, comment='Zone2上限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone3_lower', sa.Integer(), nullable=True, comment='Zone3下限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone3_upper', sa.Integer(), nullable=True, comment='Zone3上限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone4_lower', sa.Integer(), nullable=True, comment='Zone4下限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone4_upper', sa.Integer(), nullable=True, comment='Zone4上限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone5_lower', sa.Integer(), nullable=True, comment='Zone5下限心率(bpm)'))
    op.add_column('polar_exercises', sa.Column('zone5_upper', sa.Integer(), nullable=True, comment='Zone5上限心率(bpm)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polar_exercises', 'zone5_upper')
    op.drop_column('polar_exercises', 'zone5_lower')
    op.drop_column('polar_exercises', 'zone4_upper')
    op.drop_column('polar_exercises', 'zone4_lower')
    op.drop_column('polar_exercises', 'zone3_upper')
    op.drop_column('polar_exercises', 'zone3_lower')
    op.drop_column('polar_exercises', 'zone2_upper')
    op.drop_column('polar_exercises', 'zone2_lower')
    op.drop_column('polar_exercises', 'zone1_upper')
    op.drop_column('polar_exercises', 'zone1_lower')
    # ### end Alembic commands ###
