"""Add Oura cardiovascular age, resilience, and VO2 max tables

Revision ID: 79ba7bc4ab5d
Revises: 2bdecefa54e2
Create Date: 2025-11-21 14:27:33.225328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79ba7bc4ab5d'
down_revision = '2bdecefa54e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oura_cardiovascular_age',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oura_id', sa.String(length=100), nullable=False, comment='Oura唯一ID'),
    sa.Column('day', sa.Date(), nullable=False, comment='日期'),
    sa.Column('vascular_age', sa.Integer(), nullable=True, comment='血管年龄(岁)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oura_cardiovascular_age_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oura_cardiovascular_age')),
    sa.UniqueConstraint('oura_id', name=op.f('uq_oura_cardiovascular_age_oura_id'))
    )
    op.create_index('idx_oura_cv_age_user_day', 'oura_cardiovascular_age', ['user_id', 'day'], unique=False)
    op.create_table('oura_resilience',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oura_id', sa.String(length=100), nullable=False, comment='Oura唯一ID'),
    sa.Column('day', sa.Date(), nullable=False, comment='日期'),
    sa.Column('level', sa.String(length=50), nullable=True, comment='韧性等级(limited/adequate/solid/strong)'),
    sa.Column('sleep_recovery', sa.Integer(), nullable=True, comment='睡眠恢复贡献(0-100)'),
    sa.Column('daytime_recovery', sa.Integer(), nullable=True, comment='日间恢复贡献(0-100)'),
    sa.Column('stress', sa.Integer(), nullable=True, comment='压力评分(0-100)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oura_resilience_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oura_resilience')),
    sa.UniqueConstraint('oura_id', name=op.f('uq_oura_resilience_oura_id'))
    )
    op.create_index('idx_oura_resilience_user_day', 'oura_resilience', ['user_id', 'day'], unique=False)
    op.create_table('oura_vo2_max',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('oura_id', sa.String(length=100), nullable=False, comment='Oura唯一ID'),
    sa.Column('day', sa.Date(), nullable=False, comment='日期'),
    sa.Column('vo2_max', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='VO2 Max(ml/kg/min)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oura_vo2_max_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oura_vo2_max')),
    sa.UniqueConstraint('oura_id', name=op.f('uq_oura_vo2_max_oura_id'))
    )
    op.create_index('idx_oura_vo2_max_user_day', 'oura_vo2_max', ['user_id', 'day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_oura_vo2_max_user_day', table_name='oura_vo2_max')
    op.drop_table('oura_vo2_max')
    op.drop_index('idx_oura_resilience_user_day', table_name='oura_resilience')
    op.drop_table('oura_resilience')
    op.drop_index('idx_oura_cv_age_user_day', table_name='oura_cardiovascular_age')
    op.drop_table('oura_cardiovascular_age')
    # ### end Alembic commands ###
