"""Add Oura sleep contributors, embedded readiness and activity contributors

Revision ID: 8380bf62dc29
Revises: b0c98015f712
Create Date: 2025-11-23 11:48:02.652047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8380bf62dc29'
down_revision = 'b0c98015f712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oura_daily_activity', sa.Column('contributor_stay_active', sa.Integer(), nullable=True, comment='保持活跃评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('contributor_recovery_time', sa.Integer(), nullable=True, comment='恢复时间评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('contributor_move_every_hour', sa.Integer(), nullable=True, comment='每小时移动评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('contributor_training_volume', sa.Integer(), nullable=True, comment='训练量评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('contributor_training_frequency', sa.Integer(), nullable=True, comment='训练频率评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('contributor_meet_daily_targets', sa.Integer(), nullable=True, comment='达成每日目标评分(0-100)'))
    op.add_column('oura_daily_activity', sa.Column('non_wear_time', sa.Integer(), nullable=True, comment='未佩戴时间(秒)'))
    op.add_column('oura_daily_activity', sa.Column('meters_to_target', sa.Integer(), nullable=True, comment='距离目标(米)'))
    op.add_column('oura_daily_activity', sa.Column('inactivity_alerts', sa.Integer(), nullable=True, comment='久坐提醒次数'))
    op.add_column('oura_daily_activity', sa.Column('average_met_minutes', sa.DECIMAL(precision=8, scale=4), nullable=True, comment='平均MET分钟'))
    op.add_column('oura_daily_readiness', sa.Column('sleep_regularity', sa.Integer(), nullable=True, comment='睡眠规律性分数(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_total_sleep', sa.Integer(), nullable=True, comment='总睡眠时长贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_efficiency', sa.Integer(), nullable=True, comment='效率贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_restfulness', sa.Integer(), nullable=True, comment='安稳度贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_rem_sleep', sa.Integer(), nullable=True, comment='REM睡眠贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_deep_sleep', sa.Integer(), nullable=True, comment='深睡贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_latency', sa.Integer(), nullable=True, comment='入睡延迟贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('contributor_timing', sa.Integer(), nullable=True, comment='睡眠时间贡献分(0-100)'))
    op.add_column('oura_sleep', sa.Column('sleep_type', sa.String(length=20), nullable=True, comment='睡眠类型(long_sleep/nap)'))
    op.add_column('oura_sleep', sa.Column('time_in_bed', sa.Integer(), nullable=True, comment='在床时间(秒)'))
    op.add_column('oura_sleep', sa.Column('latency', sa.Integer(), nullable=True, comment='入睡延迟(秒)'))
    op.add_column('oura_sleep', sa.Column('restless_periods', sa.Integer(), nullable=True, comment='躁动次数'))
    op.add_column('oura_sleep', sa.Column('readiness_score_embedded', sa.Integer(), nullable=True, comment='嵌入的准备度评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_sleep_balance', sa.Integer(), nullable=True, comment='睡眠平衡评分(0-100，睡眠债务指标)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_previous_night', sa.Integer(), nullable=True, comment='前夜睡眠评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_recovery_index', sa.Integer(), nullable=True, comment='恢复指数(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_activity_balance', sa.Integer(), nullable=True, comment='活动平衡评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_body_temperature', sa.Integer(), nullable=True, comment='体温评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_resting_heart_rate', sa.Integer(), nullable=True, comment='静息心率评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_hrv_balance', sa.Integer(), nullable=True, comment='HRV平衡评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_contributor_previous_day_activity', sa.Integer(), nullable=True, comment='前日活动评分(0-100)'))
    op.add_column('oura_sleep', sa.Column('readiness_temperature_deviation', sa.DECIMAL(precision=4, scale=2), nullable=True, comment='体温偏差(°C)'))
    op.add_column('oura_sleep', sa.Column('readiness_temperature_trend_deviation', sa.DECIMAL(precision=4, scale=2), nullable=True, comment='体温趋势偏差(°C)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oura_sleep', 'readiness_temperature_trend_deviation')
    op.drop_column('oura_sleep', 'readiness_temperature_deviation')
    op.drop_column('oura_sleep', 'readiness_contributor_previous_day_activity')
    op.drop_column('oura_sleep', 'readiness_contributor_hrv_balance')
    op.drop_column('oura_sleep', 'readiness_contributor_resting_heart_rate')
    op.drop_column('oura_sleep', 'readiness_contributor_body_temperature')
    op.drop_column('oura_sleep', 'readiness_contributor_activity_balance')
    op.drop_column('oura_sleep', 'readiness_contributor_recovery_index')
    op.drop_column('oura_sleep', 'readiness_contributor_previous_night')
    op.drop_column('oura_sleep', 'readiness_contributor_sleep_balance')
    op.drop_column('oura_sleep', 'readiness_score_embedded')
    op.drop_column('oura_sleep', 'restless_periods')
    op.drop_column('oura_sleep', 'latency')
    op.drop_column('oura_sleep', 'time_in_bed')
    op.drop_column('oura_sleep', 'sleep_type')
    op.drop_column('oura_sleep', 'contributor_timing')
    op.drop_column('oura_sleep', 'contributor_latency')
    op.drop_column('oura_sleep', 'contributor_deep_sleep')
    op.drop_column('oura_sleep', 'contributor_rem_sleep')
    op.drop_column('oura_sleep', 'contributor_restfulness')
    op.drop_column('oura_sleep', 'contributor_efficiency')
    op.drop_column('oura_sleep', 'contributor_total_sleep')
    op.drop_column('oura_daily_readiness', 'sleep_regularity')
    op.drop_column('oura_daily_activity', 'average_met_minutes')
    op.drop_column('oura_daily_activity', 'inactivity_alerts')
    op.drop_column('oura_daily_activity', 'meters_to_target')
    op.drop_column('oura_daily_activity', 'non_wear_time')
    op.drop_column('oura_daily_activity', 'contributor_meet_daily_targets')
    op.drop_column('oura_daily_activity', 'contributor_training_frequency')
    op.drop_column('oura_daily_activity', 'contributor_training_volume')
    op.drop_column('oura_daily_activity', 'contributor_move_every_hour')
    op.drop_column('oura_daily_activity', 'contributor_recovery_time')
    op.drop_column('oura_daily_activity', 'contributor_stay_active')
    # ### end Alembic commands ###
