"""Add ai_model field to meal_records

Revision ID: b0c98015f712
Revises: 26b44259a555
Create Date: 2025-11-22 16:19:04.815591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0c98015f712'
down_revision = '26b44259a555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_records', sa.Column('ai_model', sa.String(length=100), nullable=True, comment='使用的AI模型名称（如 gemini-3-pro-preview）'))
    op.alter_column('meal_records', 'gemini_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='AI完整输出（包含分析、建议等）',
               existing_comment='Gemini完整输出（包含分析、建议等）',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal_records', 'gemini_analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Gemini完整输出（包含分析、建议等）',
               existing_comment='AI完整输出（包含分析、建议等）',
               existing_nullable=True)
    op.drop_column('meal_records', 'ai_model')
    # ### end Alembic commands ###
