"""Initial migration

Revision ID: e66756258553
Revises: 
Create Date: 2025-11-16 13:41:52.898325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e66756258553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True, comment='最大心率'),
    sa.Column('resting_hr', sa.Integer(), nullable=True, comment='静息心率'),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='体重(kg)'),
    sa.Column('height', sa.Integer(), nullable=True, comment='身高(cm)'),
    sa.Column('health_goal', sa.String(length=500), nullable=True, comment='健康目标'),
    sa.Column('training_plan', sa.String(length=200), nullable=True, comment='训练方案'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='建议日期'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='AI提供商(deepseek/openai/claude)'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='使用的模型'),
    sa.Column('summary', sa.Text(), nullable=False, comment='一句话总结'),
    sa.Column('training_advice', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='训练建议'),
    sa.Column('risk_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='风险评估'),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='行动清单'),
    sa.Column('cardiovascular_insights', sa.Text(), nullable=True, comment='心血管健康分析'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='输入Token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='输出Token数'),
    sa.Column('user_rating', sa.Integer(), nullable=True, comment='用户评分(1-5)'),
    sa.Column('user_feedback', sa.Text(), nullable=True, comment='用户反馈'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations')),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date_ai')
    )
    op.create_table('daily_training_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='训练日期'),
    sa.Column('total_duration_min', sa.Integer(), nullable=False, comment='总时长(分钟)'),
    sa.Column('zone2_min', sa.Integer(), nullable=False, comment='Zone2时长(分钟)'),
    sa.Column('hi_min', sa.Integer(), nullable=False, comment='高强度时长(分钟)'),
    sa.Column('trimp', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='训练负荷'),
    sa.Column('sessions_count', sa.Integer(), nullable=False, comment='训练次数'),
    sa.Column('total_calories', sa.Integer(), nullable=True, comment='总卡路里'),
    sa.Column('avg_hr', sa.Integer(), nullable=True, comment='平均心率'),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='风险标记'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_training_summary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_training_summary')),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_date')
    )
    op.create_table('polar_auth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('polar_user_id', sa.String(length=100), nullable=True, comment='Polar用户ID'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='刷新令牌'),
    sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='令牌过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_polar_auth_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polar_auth')),
    sa.UniqueConstraint('user_id', name=op.f('uq_polar_auth_user_id'))
    )
    op.create_table('polar_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.String(length=100), nullable=False, comment='Polar唯一ID'),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sport_type', sa.String(length=50), nullable=True, comment='运动类型'),
    sa.Column('duration_sec', sa.Integer(), nullable=False, comment='总时长(秒)'),
    sa.Column('avg_hr', sa.Integer(), nullable=True, comment='平均心率'),
    sa.Column('max_hr', sa.Integer(), nullable=True, comment='最大心率'),
    sa.Column('zone1_sec', sa.Integer(), nullable=False, comment='Zone1时长(秒)'),
    sa.Column('zone2_sec', sa.Integer(), nullable=False, comment='Zone2时长(秒)'),
    sa.Column('zone3_sec', sa.Integer(), nullable=False, comment='Zone3时长(秒)'),
    sa.Column('zone4_sec', sa.Integer(), nullable=False, comment='Zone4时长(秒)'),
    sa.Column('zone5_sec', sa.Integer(), nullable=False, comment='Zone5时长(秒)'),
    sa.Column('calories', sa.Integer(), nullable=True, comment='消耗卡路里'),
    sa.Column('cardio_load', sa.Integer(), nullable=True, comment='Polar训练负荷'),
    sa.Column('distance_meters', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='距离(米)'),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='完整原始数据'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_polar_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polar_exercises')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_polar_exercises_exercise_id'))
    )
    op.create_index('idx_user_start_time', 'polar_exercises', ['user_id', 'start_time'], unique=False)
    op.create_table('weekly_training_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False, comment='周起始日期(周一)'),
    sa.Column('total_duration_min', sa.Integer(), nullable=False, comment='周总时长(分钟)'),
    sa.Column('zone2_min', sa.Integer(), nullable=False, comment='周Zone2时长(分钟)'),
    sa.Column('hi_min', sa.Integer(), nullable=False, comment='周高强度时长(分钟)'),
    sa.Column('weekly_trimp', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='周训练负荷'),
    sa.Column('training_days', sa.Integer(), nullable=False, comment='训练天数'),
    sa.Column('rest_days', sa.Integer(), nullable=False, comment='休息天数'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_training_summary_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_training_summary')),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_user_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_training_summary')
    op.drop_index('idx_user_start_time', table_name='polar_exercises')
    op.drop_table('polar_exercises')
    op.drop_table('polar_auth')
    op.drop_table('daily_training_summary')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
